### ISSUE TITLE
Text scrolling issue

### ISSUE THREAD

**Issue by SiGaCode** [jure965/OpenLorem#14]
The addon works fine in Chrome, but in Firefox (58.0.2 on Win10) I see a weird issue when trying to scroll the generated text in the original-size textbox. The text stays in place while (the same) "ghost text" scrolls over it (couldn´t come up with a better way to describe it, see the gif).
As soon as I resize the textbox, it works. Not sure if it´s a bug or some setting in my FF though?
http://recordit.co/aRKch3crKi

**Comment by BojanKogoj** [comment]
This is most likely a bug in Firefox (on Windows only). I'll take a look at it anyway, maybe I can find a fix.
I should also block window resize, looks weird.

**Comment by jure965** [comment]
Could not replicate on Firefox 78.0.1 (Win10). If this issue persists, please reopen.
