### ISSUE TITLE
This is a cool and very useful add on, thanks!

### ISSUE THREAD

**Issue by bisonbleu** [jure965/OpenLorem#8]
And now, this is a feature request. It would be great if one could simply right-click in a field to populate it with some Lorem ipsum (from a contextual menu). Possible?

In the old days, there was an Add on named 'Dummy Lipsum' (now defunct) which did just that and it was super useful. :-)

**Comment by jure965** [comment]
This is a very good idea. We will look into it, if it's possible with webextensions. Thank you for your feedback.

**Comment by BojanKogoj** [comment]
@bisonbleu and @jure965, I could use some advice. 

I managed to get most of it working, however, the content_script that adds text to the clicked field doesn't have access to the [loader](https://github.com/jure965/OpenLorem/blob/master/extension/popup/scripts/loader.js) (which actually loads data). Also, waiting for network reply in this situation might not be the best.

Would it be ok if data (Lorem ipsum) came from a predefined text, stored locally, and ignore other providers?

**Comment by bisonbleu** [comment]
@BojanKogoj, I think 'predefined text' is smart, more efficient and likely covers more than 95% of use cases. Generic hard coded Lorem ipsum is all I need, 4 or 5 paragraphs. The provider feature is nice the first and second time, but after that it's a choice I don't need, it falls into the category of unwanted bells and whistles. ;-)

**Comment by BojanKogoj** [comment]
@bisonbleu Took me way too long, but it's finally done! You will probably need to enable it through options. I will upload update shortly.

![image](https://user-images.githubusercontent.com/634075/31320407-5a7902ca-ac74-11e7-8353-4f29118ed1ff.png)

**Comment by bisonbleu** [comment]
I know the feeling @BojanKogoj. That happens to me regularly. I've learned to accept that sometimes, that's just the way it is. In hindsight, it's usually well worth it.

Works great! Very nice addition, definitely worth a large beer! ;-)
